SD_MODELS_DIR=/home/dell/ZDisk/Workspace/2023-07-01/sd_models

link:
	ln -s ${SD_MODELS_DIR}/sdxl1.0/sdxl_vae.safetensors .
	ln -s ${SD_MODELS_DIR}/sdxl1.0/sd_xl_*_1.0.safetensors* .
	ln -s ${SD_MODELS_DIR}/sdxl1.0/clip_vision_g.safetensors .
	ln -s ${SD_MODELS_DIR}/sdxl1.0/control-lora-*.safetensors .
clean:
	rm -rf *.safetensors

